#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/.terminals/_dev_pts_1/dev_1/._/._/._/tests/basics/34.js
# Generated at: 2026-08-26T05:58:07Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/.terminals/_dev_pts_1/dev_1/._/._/._/tests/basics/34.js

cat << 'NODEOUTPUT'
321
123
eita
321
NODEOUTPUT

exit 0
