#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/.terminals/_dev_pts_1/dev_1/._/._/._/tests/basics/35.js
# Generated at: 2026-08-26T10:00:03Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/.terminals/_dev_pts_1/dev_1/._/._/._/tests/basics/35.js

cat << 'NODEOUTPUT'
Usuario 
daniel
 cadastrado com sucesso !
idade : 
20
------ fim ------
Usuario 
teste
 cadastrado com sucesso !
idade : 
25
------ fim ------
Usuario 
otro
 cadastrado com sucesso !
idade : 
30
------ fim ------
NODEOUTPUT

exit 0
