#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/raw/.terminals/_dev_pts_5/dev_1/._/._/._/tests/basics/36.js
# Generated at: 2026-08-26T21:13:59Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/raw/.terminals/_dev_pts_5/dev_1/._/._/._/tests/basics/36.js

cat << 'NODEOUTPUT'
2
2
2
2
2
3
3
10
10
10
20
20
30
30
1
1
1
1
1
1
1
NODEOUTPUT

exit 0
