#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/raw/.terminals/_dev_pts_5/dev_1/._/._/._/tests/basics/37.js
# Generated at: 2026-08-26T22:49:23Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/raw/.terminals/_dev_pts_5/dev_1/._/._/._/tests/basics/37.js

cat << 'NODEOUTPUT'
11.833333333333332
NODEOUTPUT

exit 0
