#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/raw/.terminals/_dev_pts_2/dev_1/._/._/._/tests/basics/41.js
# Generated at: 2026-09-24T20:33:59Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/raw/.terminals/_dev_pts_2/dev_1/._/._/._/tests/basics/41.js

cat << 'NODEOUTPUT'
13
21
71.66666666666667
203
5349.5
10519.833333333332
1411907.5
NODEOUTPUT

exit 0
